// closed — air-gapped: local slots only, a local judge, deny-all egress, hands
// under sbx lockdown. The lane seals swarm.airgap with the policy hash and the
// egress count mcpsnoop saw on the wire (must be 0).
// Generated by lanes/swarm/presets.mjs write — edit the table there, then vet.
package swarm

swarm: {
	v:        1
	id:       "closed-3"
	preset:   "closed-3"
	topology: "closed"
	members: [
		{id: "air-1", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL", provider: "ollama:mac", node: "mac", sandbox: "closed"},
		{id: "air-2", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL", provider: "ollama:mac", node: "mac", sandbox: "closed"},
		{id: "air-3", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL", provider: "ollama:mac", node: "mac", sandbox: "closed"},
	]
	size:    3
	budget:  {usd: 0, max_calls: 8}
	judge:   {tier: "local", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL"}
	network: {policy: "closed", egress_allow: []}
}
