// coordinator — the judge-tier model splits the task, members take a part each,
// the coordinator composes the answer.
// Generated by lanes/swarm/presets.mjs write — edit the table there, then vet.
package swarm

swarm: {
	v:        1
	id:       "coordinator-3"
	preset:   "coordinator-3"
	topology: "coordinator"
	members: [
		{id: "w-1", kind: "model", model: "google/gemini-3.7-flash", provider: "openrouter"},
		{id: "w-2", kind: "model", model: "x-ai/grok-4.6", provider: "openrouter"},
		{id: "w-3", kind: "model", model: "google/gemini-3.7-flash", provider: "openrouter"},
	]
	size:    3
	budget:  {usd: 0.3, max_calls: 8}
	judge:   {tier: "edge", model: "x-ai/grok-4.6"}
	network: {policy: "open"}
}
