// council — rounds of positions, then a vote; no member may vote for itself.
// Generated by lanes/swarm/presets.mjs write — edit the table there, then vet.
package swarm

swarm: {
	v:        1
	id:       "council-3"
	preset:   "council-3"
	topology: "council"
	rounds:   2
	members: [
		{id: "seat-1", kind: "model", model: "google/gemini-3.7-flash", provider: "openrouter"},
		{id: "seat-2", kind: "model", model: "x-ai/grok-4.6", provider: "openrouter"},
		{id: "seat-3", kind: "model", model: "google/gemini-3.7-flash", provider: "openrouter", weight: 2},
	]
	size:    3
	budget:  {usd: 0.4, max_calls: 12}
	judge:   {tier: "edge", model: "x-ai/grok-4.6"}
	network: {policy: "open"}
}
