// crew — local harnesses with roles derived from harness.abilities
// (builder / operator / bridge / answerer), planned and composed by the judge.
// Generated by lanes/swarm/presets.mjs write — edit the table there, then vet.
package swarm

swarm: {
	v:        1
	id:       "crew-3"
	preset:   "crew-3"
	topology: "crew"
	members: [
		{id: "jcode", kind: "harness", harness: "jcode", model: "google/gemini-3.7-flash", node: "mac"},
		{id: "opencode", kind: "harness", harness: "opencode", model: "google/gemini-3.7-flash", node: "mac"},
		{id: "hermes", kind: "harness", harness: "hermes", model: "google/gemini-3.7-flash", node: "mac"},
	]
	size:    3
	budget:  {usd: 0.5, max_calls: 12, max_ms: 900000}
	judge:   {tier: "edge", model: "google/gemini-3.7-flash"}
	network: {policy: "open"}
}
