// fanout — every member answers; all answers are kept side by side.
// Generated by lanes/swarm/presets.mjs write — edit the table there, then vet.
package swarm

swarm: {
	v:        1
	id:       "fanout-2"
	preset:   "fanout-2"
	topology: "fanout"
	members: [
		{id: "a", kind: "model", model: "google/gemini-3.7-flash", provider: "openrouter"},
		{id: "b", kind: "model", model: "x-ai/grok-4.6", provider: "openrouter"},
	]
	size:    2
	budget:  {usd: 0.1, max_calls: 4}
	judge:   {tier: "edge"}
	network: {policy: "open"}
}
