// fusion — every member answers, one judge merges.
// Generated by lanes/swarm/presets.mjs write — edit the table there, then vet.
package swarm

swarm: {
	v:        1
	id:       "fusion-2"
	preset:   "fusion-2"
	topology: "fusion"
	members: [
		{id: "a", kind: "model", model: "google/gemini-3.7-flash", provider: "openrouter"},
		{id: "b", kind: "model", model: "x-ai/grok-4.6", provider: "openrouter"},
	]
	size:    2
	budget:  {usd: 0.15, max_calls: 4}
	judge:   {tier: "edge", model: "x-ai/grok-4.6"}
	network: {policy: "open"}
}
