// "Kimi 5" — five Kimi sessions through Ollama Cloud (the local daemon proxies
// kimi-k3:cloud to ollama.com). Metered on the operator's Ollama account.
// Generated by lanes/swarm/presets.mjs write — edit the table there, then vet.
package swarm

swarm: {
	v:        1
	id:       "kimi-5"
	preset:   "kimi-5"
	topology: "fusion"
	members: [
		{id: "kimi-1", kind: "model", model: "kimi-k3:cloud", provider: "ollama-cloud", node: "mac"},
		{id: "kimi-2", kind: "model", model: "kimi-k3:cloud", provider: "ollama-cloud", node: "mac"},
		{id: "kimi-3", kind: "model", model: "kimi-k3:cloud", provider: "ollama-cloud", node: "mac"},
		{id: "kimi-4", kind: "model", model: "kimi-k3:cloud", provider: "ollama-cloud", node: "mac"},
		{id: "kimi-5", kind: "model", model: "kimi-k3:cloud", provider: "ollama-cloud", node: "mac"},
	]
	size:    5
	budget:  {usd: 0.5, max_calls: 8}
	judge:   {tier: "local", model: "kimi-k3:cloud"}
	network: {policy: "open"}
}
