// "Local 5" on this Mac's second Ollama server (port 11435, OLLAMA_NUM_PARALLEL=5):
// the fallback proof while spark2 is off the tailnet.
// Generated by lanes/swarm/presets.mjs write — edit the table there, then vet.
package swarm

swarm: {
	v:        1
	id:       "local-5-mac"
	preset:   "local-5-mac"
	topology: "fanout"
	members: [
		{id: "slot-1", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL", provider: "ollama:mac", node: "mac"},
		{id: "slot-2", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL", provider: "ollama:mac", node: "mac"},
		{id: "slot-3", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL", provider: "ollama:mac", node: "mac"},
		{id: "slot-4", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL", provider: "ollama:mac", node: "mac"},
		{id: "slot-5", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL", provider: "ollama:mac", node: "mac"},
	]
	size:    5
	budget:  {usd: 0, max_calls: 12}
	judge:   {tier: "local", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL"}
	network: {policy: "tailnet"}
}
