// "Local 5" — five parallel Ollama slots on spark2 (Level 0). fanout, then a
// second run as fusion, is the proof the order asks for.
// Generated by lanes/swarm/presets.mjs write — edit the table there, then vet.
package swarm

swarm: {
	v:        1
	id:       "local-5"
	preset:   "local-5"
	topology: "fanout"
	members: [
		{id: "slot-1", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q8_K_XL", provider: "ollama:spark2", node: "spark2"},
		{id: "slot-2", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q8_K_XL", provider: "ollama:spark2", node: "spark2"},
		{id: "slot-3", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q8_K_XL", provider: "ollama:spark2", node: "spark2"},
		{id: "slot-4", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q8_K_XL", provider: "ollama:spark2", node: "spark2"},
		{id: "slot-5", kind: "model", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q8_K_XL", provider: "ollama:spark2", node: "spark2"},
	]
	size:    5
	budget:  {usd: 0, max_calls: 12}
	judge:   {tier: "local", model: "hf.co/unsloth/Qwen3.8-27B-GGUF:UD-Q8_K_XL"}
	network: {policy: "tailnet"}
}
