// relay — a handoff chain: each member improves the previous member's answer.
// Generated by lanes/swarm/presets.mjs write — edit the table there, then vet.
package swarm

swarm: {
	v:        1
	id:       "relay-3"
	preset:   "relay-3"
	topology: "relay"
	members: [
		{id: "draft", kind: "model", model: "google/gemini-3.7-flash", provider: "openrouter"},
		{id: "critic", kind: "model", model: "x-ai/grok-4.6", provider: "openrouter"},
		{id: "final", kind: "model", model: "google/gemini-3.7-flash", provider: "openrouter"},
	]
	size:    3
	budget:  {usd: 0.2, max_calls: 6}
	judge:   {tier: "edge"}
	network: {policy: "open"}
}
