// "Timmy ×3" — Level 2: the root commander (war-room) runs three project
// Timmys as tools over MCP (Durable Object RPC) and fuses their answers.
// Generated by lanes/swarm/presets.mjs write — edit the table there, then vet.
package swarm

swarm: {
	v:        1
	id:       "timmy-x3"
	preset:   "timmy-x3"
	topology: "fusion"
	members: [
		{id: "ship", kind: "timmy", room: "project:ship"},
		{id: "shelf", kind: "timmy", room: "project:shelf"},
		{id: "swarm", kind: "timmy", room: "project:swarm"},
	]
	size:    3
	budget:  {usd: 0.25, max_calls: 8}
	judge:   {tier: "edge", model: "google/gemini-3.7-flash"}
	network: {policy: "open"}
}
