// tournament — N candidates, the judge picks one, the losers are sealed too.
// Generated by lanes/swarm/presets.mjs write — edit the table there, then vet.
package swarm

swarm: {
	v:        1
	id:       "tournament-4"
	preset:   "tournament-4"
	topology: "tournament"
	members: [
		{id: "cand-1", kind: "model", model: "google/gemini-3.7-flash", provider: "openrouter"},
		{id: "cand-2", kind: "model", model: "x-ai/grok-4.6", provider: "openrouter"},
		{id: "cand-3", kind: "model", model: "google/gemini-3.7-flash", provider: "openrouter"},
		{id: "cand-4", kind: "model", model: "x-ai/grok-4.6", provider: "openrouter"},
	]
	size:    4
	budget:  {usd: 0.3, max_calls: 8}
	judge:   {tier: "edge", model: "x-ai/grok-4.6"}
	network: {policy: "open"}
}
