#!/usr/bin/env node
// timmy privacy journal — docs/JOURNAL.md from the private orders ledger (ORDER blank-slate-v1k9).
//
//   node lanes/privacy/journal.mjs                       regenerate docs/JOURNAL.md from .timmy/private/orders.log
//   node lanes/privacy/journal.mjs --check               exit 1 when docs/JOURNAL.md is stale or carries a finding
//   node lanes/privacy/journal.mjs --seed-from <ref>     seed .timmy/private/orders.log from git (`<ref>:orders.log`)
//                                                        when the overlay has no ledger yet (never overwrites)
//
// The ledger (ORD-ID | ts | actor | order | evidence) is operator-private: it names hosts, paths and
// people. The public journal keeps every order line with every pattern match — all severities, hashed
// identity terms included — replaced by `[pattern.id]`, then asserts the result scans clean.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadPatterns, scanText, TOKEN_RX } from './scan.mjs';

const ROOT = resolve(fileURLToPath(new URL('.', import.meta.url)), '..', '..');
const PRIVATE_DIR = process.env.TIMMY_PRIVATE_DIR || join(ROOT, '.timmy', 'private');
const args = process.argv.slice(2);
const flag = (k, d) => { const i = args.indexOf(k); return i >= 0 && args[i + 1] !== undefined && !args[i + 1].startsWith('--') ? args[i + 1] : d; };
const IN = resolve(flag('--in', join(PRIVATE_DIR, 'orders.log')));
const OUT = resolve(flag('--out', join(ROOT, 'docs', 'JOURNAL.md')));

/** Every match of every pattern (all severities) and every hashed term → [id]. Allow-listed lines pass untouched. */
export function sanitizeLine(line, P) {
  if (P.allow.some((a) => a.test(line))) return line;
  let out = line;
  for (const p of P.patterns) { p.rx.lastIndex = 0; out = out.replace(p.rx, `[${p.id}]`); }
  if (P.hashed?.size) {
    TOKEN_RX.lastIndex = 0;
    out = out.replace(TOKEN_RX, (t) => {
      const h = P.hashed.get(createSha(t.toLowerCase()));
      return h ? `[${h.id}]` : t;
    });
  }
  return out;
}
import { createHash } from 'node:crypto';
const createSha = (s) => createHash('sha256').update(s).digest('hex');

export function renderJournal(ledgerText, P) {
  const rows = [];
  for (const raw of ledgerText.split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const parts = line.split(' | ');
    const [id, ts, actor, ...rest] = parts;
    const evidence = rest.length > 1 ? rest.pop() : '';
    const order = rest.join(' | ');
    rows.push({ id: sanitizeLine(id ?? '', P), date: (ts ?? '').slice(0, 10), actor: sanitizeLine(actor ?? '', P), order: sanitizeLine(order, P), evidence: sanitizeLine(evidence, P) });
  }
  const out = ['# JOURNAL — executed orders (sanitized)', '',
    'Generated by `node lanes/privacy/journal.mjs` from the operator-private ledger (`.timmy/private/orders.log`).',
    'Every privacy-pattern match — hosts, paths, people, hashed identity terms — is replaced by `[pattern.id]`.',
    'Do not edit by hand; regenerate. `--check` fails the build when this file is stale or unclean.', '',
    `Orders: ${rows.length}`, ''];
  for (const r of rows) out.push(`- **${r.id}** · ${r.date} · ${r.actor} — ${r.order}${r.evidence ? `\n  _evidence:_ ${r.evidence}` : ''}`);
  return out.join('\n') + '\n';
}

if (process.argv[1]?.endsWith('journal.mjs')) {
  const P = loadPatterns();
  const seed = flag('--seed-from');
  if (seed) {
    if (existsSync(IN)) { console.log(JSON.stringify({ ok: true, note: 'overlay ledger already present; not overwritten', ledger: IN })); process.exit(0); }
    const r = spawnSync('git', ['show', `${seed}:orders.log`], { cwd: ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
    if (r.status !== 0) { console.error(`[journal] no orders.log at ${seed}`); process.exit(2); }
    mkdirSync(dirname(IN), { recursive: true }); writeFileSync(IN, r.stdout, { mode: 0o600 });
    console.log(JSON.stringify({ ok: true, seeded: relative(ROOT, IN), from: seed, lines: r.stdout.split('\n').filter((l) => l && !l.startsWith('#')).length }));
    process.exit(0);
  }
  if (!existsSync(IN)) { console.error(`[journal] no ledger at ${relative(ROOT, IN)} — seed it: node lanes/privacy/journal.mjs --seed-from <ref>`); process.exit(2); }
  const md = renderJournal(readFileSync(IN, 'utf8'), P);
  const findings = scanText(md, relative(ROOT, OUT), P, 'journal');
  if (findings.length) { console.error(`[journal] the sanitized journal still carries ${findings.length} finding(s): ${[...new Set(findings.map((f) => f.pattern))].join(', ')}`); process.exit(1); }
  if (args.includes('--check')) {
    const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
    const ok = cur === md;
    console.log(JSON.stringify({ ok, journal: relative(ROOT, OUT), note: ok ? 'journal is current and clean' : 'journal is STALE: regenerate with node lanes/privacy/journal.mjs' }));
    process.exit(ok ? 0 : 1);
  }
  mkdirSync(dirname(OUT), { recursive: true }); writeFileSync(OUT, md);
  console.log(JSON.stringify({ ok: true, journal: relative(ROOT, OUT), orders: md.split('\n').filter((l) => l.startsWith('- **')).length, findings: 0 }));
}
